### ISSUE TITLE
Error on my mac

### ISSUE THREAD

**Issue by erlebach** [anand-kamble/LLM-experiments#1]
I followed all the instructions, and installed Python via Poetry (I have done this many times before).  Here is the error I get: 
```
(ollama-py3.10) ➜  Ollama git:(main) ✗ python Ollama-chat.py
You can use following commands in chat
 /save : to save the chat to json file.
 /bye : to exit Ollama Chat.

Write a Message for llama2
>  How are you doing?
Traceback (most recent call last):
  File "/Users/erlebach/src/2024/LLM-experiments/Ollama/Ollama-chat.py", line 123, in <module>
    ollama.load_chat().init()
  File "/Users/erlebach/src/2024/LLM-experiments/Ollama/Ollama-chat.py", line 118, in init
    asyncio.run(self.chat_request())
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/erlebach/src/2024/LLM-experiments/Ollama/Ollama-chat.py", line 81, in chat_request
    self.chat['messages'].append(res['message'])
KeyError: 'message'
```
It is not clear why I get this error. Can you help?

**Comment by anand-kamble** [comment]
Hello Prof., 
I have never faced this issue before, I will look into it. And let you know.

**Comment by erlebach** [comment]
All I had to do is change models. Ollama did not work with Llama2. I am running Mistral. How do I use `index.html`? The next step is to learn how to interact with the grade assignments. To do that, I will read the `pickle` files and experiment. We should discuss this.

**Comment by anand-kamble** [comment]
Reopening since I accidentally closed it.

**Comment by erlebach** [comment]
THe reason for the error is clear. WHen I type `ollama list`, here are the models I can run. You have a different list: 
```
NAME                               	ID          	SIZE  	MODIFIED
MODEL_CODELLAMA:7B-PYTHON_T0_CTX512	983eca162f34	3.8 GB	2 weeks ago
MODEL_TINYLLAMA:1.1B_T0.6_CTX512   	95e4f4e23e0d	637 MB	2 weeks ago
MODEL_TINYLLAMA:1.1B_T0_CTX512     	c133a2e3a7eb	637 MB	2 weeks ago
MODEL_TINYLLAMA:1.1B_T1.2_CTX512   	2aba606f2644	637 MB	2 weeks ago
T0:latest                          	635fc5f35d3c	26 GB 	3 weeks ago
T1:latest                          	bb977623b461	26 GB 	3 weeks ago
codellama:13b                      	9a874ed1c056	7.3 GB	6 months ago
codellama:13b-code                 	9f684b95053a	7.3 GB	6 months ago
codellama:7b-code                  	2595b26103b8	3.8 GB	6 months ago
codellama:7b-instruct              	36893bf9bc7f	3.8 GB	6 months ago
codellama:7b-python                	120ca3419eae	3.8 GB	2 weeks ago
codellama:latest                   	36893bf9bc7f	3.8 GB	6 months ago
codeup:latest                      	27eb143eca22	7.4 GB	6 months ago
ge:latest                          	b54f718751a0	3.8 GB	6 months ago
ge_model:latest                    	639403055da9	3.8 GB	6 months ago
llama2:13b-chat                    	5c4a1bb95ee1	7.3 GB	6 months ago
llama2:13b-text                    	e52f30eaea68	7.3 GB	6 months ago
llama2:7b                          	d5611f7c428c	3.8 GB	6 months ago
llama2:chat                        	d5611f7c428c	3.8 GB	6 months ago
llama2:latest                      	d5611f7c428c	3.8 GB	6 months ago
llama2:text                        	7cb8a599185f	3.8 GB	6 months ago
medllama2:7b                       	a53737ec0c72	3.8 GB	3 weeks ago
medllama2:7b-q4_K_M                	2943f4b668e1	4.1 GB	3 weeks ago
medllama2:latest                   	64197cbd6c3f	3.8 GB	6 months ago
mistral:latest                     	61e88e884507	4.1 GB	3 weeks ago
mixtral:latest                     	ee3d28ef2778	26 GB 	3 weeks ago
phi:latest                         	e2fd6321a5fe	1.6 GB	3 weeks ago
tinyllama:1.1b                     	2644915ede35	637 MB	2 weeks ago
```

**Comment by anand-kamble** [comment]
That might be the reason. The outputs from different models might have different structure of dictionaries.
